### ISSUE TITLE
Logout Endpoint Issue, when no server requested auth

### ISSUE THREAD

**Issue by thepont** [blueflag/moneypenny#46]
```
TypeError: Cannot read property 'pop' of undefined
    at logout (/home/paulesson/projects/trc-contractor-auth/node_modules/moneypenny/app/moneypenny-server/auth/logoutController.js:6:52)
    at Layer.handle [as handle_request] (/home/paulesson/projects/trc-contractor-auth/node_modules/elephas/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/paulesson/projects/trc-contractor-auth/node_modules/elephas/node_modules/express/lib/router/index.js:312:13)
    at /home/paulesson/projects/trc-contractor-auth/node_modules/elephas/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/paulesson/projects/trc-contractor-auth/node_modules/elephas/node_modules/express/lib/router/index.js:330:12)
    at next (/home/paulesson/projects/trc-contractor-auth/node_modules/elephas/node_modules/express/lib/router/index.js:271:10)
    at /home/paulesson/projects/trc-contractor-auth/node_modules/moneypenny/node_modules/oauth20-provider/lib/index.js:41:13
    at Layer.handle [as handle_request] (/home/paulesson/projects/trc-contractor-auth/node_modules/elephas/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/paulesson/projects/trc-contractor-auth/node_modules/elephas/node_modules/express/lib/router/index.js:312:13)
    at /home/paulesson/projects/trc-contractor-auth/node_modules/elephas/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/paulesson/projects/trc-contractor-auth/node_modules/elephas/node_modules/express/lib/router/index.js:330:12)
    at next (/home/paulesson/projects/trc-contractor-auth/node_modules/elephas/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/home/paulesson/projects/trc-contractor-auth/node_modules/elephas/node_modules/express/node_modules/serve-static/index.js:120:7)
    at emitOne (events.js:77:13)
    at SendStream.emit (events.js:169:7)
    at SendStream.error (/home/paulesson/projects/trc-contractor-auth/node_modules/elephas/node_modules/express/node_modules/send/index.js:245:17)
```

**Comment by thepont** [comment]
should be fixed in latest version
